<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login con js y ajax</title>
    <link rel="stylesheet" type="text/css" href="css/48.css">
    <script type="text/javascript" src="jquery/jquery-3.1.0.js"></script>
    <!--<script type="text/javascript" src="js/49.js"></script>-->
    <style>
        #noticias li {
            display: inline-block;
            margin-right: 30px;
        }
        /*#noticias li a {
         padding: 5px 10px; 
         background-color: white;
         color: black;
         text-decoration: none; 
      }*/
        /*#noticias li a:hover {
         background-color: rgb(255,153,0);
         color: white;
      }*/
        
        #contenidos_externos #noticia {
            margin-top: 10px;
            padding: 20px;
            border: 1px solid white;
        }
        
        #boton {
            background-color: rgb(255, 153, 0);
            color: #fff;
            font-weight: bold;
        }
    </style>
    <script>
        $(document).ready(function() {
            $(document).submit(function() {
                var datosForm = {
                    usuario: $("#usuario").val(),
                    contra: $("#contra").val()
                }
                $.get("js/login1.php", datosForm, procesaDatos).fail(procesaError);
                return false;
            });

            function procesaDatos(datos) {
                if (datos === "autorizado") {
                    $("#contenidos_externos").html("<p>Hola Jorge, Bienvenido</p>");
                } else {
                    $("#contenidos_externos").html("<p>Usuario no autorizado</p>");
                }
            }

            function procesaError() {
                var msError = "Ha ocurrido algo inesperado, inténtelo más tarde";
                $("#contenidos_externos").html("<p>" + msError + "</p>");
            }
        });
    </script>
</head>

<body>
    <div class="cabecera">
        <p class="logo">Procesando respuesta del servidor</p>
    </div>
    <div class="contenido">
        <div class="principal">
            <form method="get" action="login.php" id="login">
                <table>
                    <tr>
                        <td>
                            <label for="usuario">Usuario:</label>
                        </td>
                        <td>
                            <input type="text" name="usuario" id="usuario">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="contra">Contaseña: </label>
                        </td>
                        <td>
                            <input type="password" name="contra" id="contra">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">
                            <input type="submit" name="boton" id="boton" value="Enviar">
                        </td>
                    </tr>
                </table>
            </form>
            <div id="contenidos_externos"></div>
        </div>
    </div>
</body>

</html>
<!--NOTAS

    -en este ejemplo se hace uso de la función fail() para resolver un error que permita la ejecución de la funnción procesaError()
    -para lograr esto se ha cambiado el nombre del archivo php de login.php a login1.php

-->